### PR TITLE
Add a Dictation object

### PR DESCRIPTION
**Pull request by C-D-Lewis**
Locally I get `not-allowed` without the option to allow access like I get on JSBin. Apart from that the new object appears to be working. I also added a skeleton example page, but it is not yet linked to from anywhere else.

### CODE REVIEW

**Comment by HBehrens** [comment]
The changes don't pass the linter step, @C-D-Lewis :(

**Comment by C-D-Lewis** [comment]
It's `webkitSpeechRecognition`. I'm trying to find if it's needed at all as an alternative to `SpeechRecognition`. If it's widely supported it can be removed.

**Comment by C-D-Lewis** [comment]
Chrome reports:
> SpeechRecognition is not a function
But the linter doesn't like webkitSpeechRecognition. Not sure how to proceed.

**Comment by sirlantis** [comment]
@C-D-Lewis If you take a look at the top of the file will see how this is handled for other *global* classes like `XMLHttpRequest` - see the eslint documentation for [additional references](http://eslint.org/docs/user-guide/configuring#configuring-rules).

**Comment by HBehrens** [comment]
The file `symbols-manual.js` is meant for all bindings to the `transpiled.js` that cannot be generated easily. For cases like yours where technically there's no dependency to the transpiled code at all and people would benefit from a "wearable-focused" API on top of WebAPIs, we would like to see small, reusable packages that will alter become NPM modules. Unfortunately, we don't have a good example for this ,yet (will happen next sprint).
Meanwhile, do you mind, moving your convenience wrapper into a separate in your example folder?

**Comment by C-D-Lewis** [comment]
Sure, doing it now!

**Pull request closed without merging**
