### PR TITLE
Design iteration of CSS

### PR DESCRIPTION
**Pull request by sirlantis**
I found some time over the weekend to tinker with the CSS a bit (to make it less 'pragmatic'/'bootstrappy'). I guess there's a better design coming in the future, but I really wasn't happy with the current state.

While I tried to stay away from the README, I touched it in a few places in the end (it should still work when viewed on GitHub):

- Moved the 'first step' sentence above everything else as kind of a slogan. I always found the first "weird first step" headline confusing, because the mention of the 'first step' was hidden somewhere in the first paragraph.
- Only the first `Rocky.js` headline is an H1 - everything else is H2 or smaller
- Add the more common `$` prefix for bash lines.
- Restructured the section at the bottom about how to transpile the FW
- Set `Rocky.js` and other names in italic to make them easily distinguishable from regular text
- Replace PR with 'pull-request' (although maybe that dash should be a space)
- Clarified that (`grunt`) means `grunt` without arguments

Feel free to merge or ditch it.

### CODE REVIEW

**Comment by HBehrens** [comment]
At first glance, this looks pretty cool! Thank you, @sirlantis – will look at this in detail "tomorrow".

**Comment by franc0is** [comment]
Nice step forward in my opinion. Unless @cat-haines has any objections, let's merge. Thanks a lot @sirlantis !

**Comment by franc0is** [comment]
Purrrty

**Comment by HBehrens** [comment]
@cat-haines can you land this as soon as you're fine with the changes?

**Comment by cat-haines** [comment]
Fixed an issue that the new CSS brought to light on the interactive examples page.

+1

**Pull request merged**
